/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculation;

/**
 *
 * @author Asus
 */
public class calculator extends javax.swing.JFrame {
    
    double firstnum;
    double secondnum;
    double result;
    String operations;
    /**
     * Creates new form calculator
     */
    public calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtDisplay = new javax.swing.JTextField();
        jBn1 = new javax.swing.JButton();
        jBn2 = new javax.swing.JButton();
        jBn3 = new javax.swing.JButton();
        jBn4 = new javax.swing.JButton();
        jBn5 = new javax.swing.JButton();
        jBn6 = new javax.swing.JButton();
        jBn7 = new javax.swing.JButton();
        jBn8 = new javax.swing.JButton();
        jBn9 = new javax.swing.JButton();
        jBn10 = new javax.swing.JButton();
        jBn11 = new javax.swing.JButton();
        jBn12 = new javax.swing.JButton();
        jBn13 = new javax.swing.JButton();
        jBn14 = new javax.swing.JButton();
        jBn15 = new javax.swing.JButton();
        jBn16 = new javax.swing.JButton();
        jBn17 = new javax.swing.JButton();
        jBn18 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtxtDisplay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jBn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBn1.setText("1");
        jBn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBn1ActionPerformed(evt);
            }
        });

        jBn2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBn2.setText("2");
        jBn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBn2ActionPerformed(evt);
            }
        });

        jBn3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBn3.setText("3");
        jBn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBn3ActionPerformed(evt);
            }
        });

        jBn4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBn4.setText("4");
        jBn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBn4ActionPerformed(evt);
            }
        });

        jBn5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBn5.setText("5");
        jBn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBn5ActionPerformed(evt);
            }
        });

        jBn6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBn6.setText("6");
        jBn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBn6ActionPerformed(evt);
            }
        });

        jBn7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBn7.setText("7");
        jBn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBn7ActionPerformed(evt);
            }
        });

        jBn8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBn8.setText("8");
        jBn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBn8ActionPerformed(evt);
            }
        });

        jBn9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBn9.setText("9");
        jBn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBn9ActionPerformed(evt);
            }
        });

        jBn10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBn10.setText("0");
        jBn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBn10ActionPerformed(evt);
            }
        });

        jBn11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBn11.setText("+");
        jBn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBn11ActionPerformed(evt);
            }
        });

        jBn12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBn12.setText("-");
        jBn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBn12ActionPerformed(evt);
            }
        });

        jBn13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBn13.setText("/");
        jBn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBn13ActionPerformed(evt);
            }
        });

        jBn14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBn14.setText("*");
        jBn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBn14ActionPerformed(evt);
            }
        });

        jBn15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBn15.setText("+/-");
        jBn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBn15ActionPerformed(evt);
            }
        });

        jBn16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBn16.setText(".");
        jBn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBn16ActionPerformed(evt);
            }
        });

        jBn17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBn17.setText("C");
        jBn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBn17ActionPerformed(evt);
            }
        });

        jBn18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBn18.setText("=");
        jBn18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBn18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtDisplay)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBn1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBn2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBn3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBn4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBn5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBn6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBn7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBn8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBn17, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBn18, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBn9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBn10, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBn11, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBn13, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBn14, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBn15, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBn16, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBn12, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBn1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBn2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBn3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBn4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBn5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBn6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBn7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBn8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBn12, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBn10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBn9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBn11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBn13, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBn15, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBn14, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBn16, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBn17, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBn18, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBn3ActionPerformed
        String Enternumber =jtxtDisplay.getText()+ jBn3.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBn3ActionPerformed

    private void jBn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBn7ActionPerformed
        String Enternumber =jtxtDisplay.getText()+ jBn7.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBn7ActionPerformed

    private void jBn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBn9ActionPerformed
        String Enternumber =jtxtDisplay.getText()+ jBn9.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBn9ActionPerformed

    private void jBn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBn14ActionPerformed
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations="*";
    }//GEN-LAST:event_jBn14ActionPerformed

    private void jBn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBn10ActionPerformed
        String Enternumber =jtxtDisplay.getText()+ jBn10.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBn10ActionPerformed

    private void jBn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBn13ActionPerformed
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations="/";
    }//GEN-LAST:event_jBn13ActionPerformed

    private void jBn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBn17ActionPerformed
        String deletes = null;
       if(jtxtDisplay.getText().length()>0){
            StringBuilder strB=new StringBuilder(jtxtDisplay.getText());
            strB.deleteCharAt(jtxtDisplay.getText().length()-1);
            deletes=strB.toString();
            jtxtDisplay.setText(deletes);
   }
    
        
    }//GEN-LAST:event_jBn17ActionPerformed

    private void jBn18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBn18ActionPerformed
        String answer;
        
        secondnum=Double.parseDouble(jtxtDisplay.getText());
        if (operations == "+"){
            result =firstnum + secondnum;
            answer= String.format("%.2f",result);
            jtxtDisplay.setText(answer);
        }
        else if (operations == "-"){
            result =firstnum - secondnum;
            answer= String.format("%.2f",result);
            jtxtDisplay.setText(answer);
        }
        else if (operations == "*"){
            result =firstnum * secondnum;
            answer= String.format("%.2f",result);
            jtxtDisplay.setText(answer);
        }
        else if (operations == "/"){
            result =firstnum / secondnum;
            answer= String.format("%.2f",result);
            jtxtDisplay.setText(answer);
        }
    }//GEN-LAST:event_jBn18ActionPerformed

    private void jBn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBn1ActionPerformed
        String Enternumber =jtxtDisplay.getText()+ jBn1.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBn1ActionPerformed

    private void jBn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBn2ActionPerformed
        String Enternumber =jtxtDisplay.getText()+ jBn2.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBn2ActionPerformed

    private void jBn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBn4ActionPerformed
        String Enternumber =jtxtDisplay.getText()+ jBn4.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBn4ActionPerformed

    private void jBn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBn5ActionPerformed
        String Enternumber =jtxtDisplay.getText()+ jBn5.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBn5ActionPerformed

    private void jBn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBn6ActionPerformed
        String Enternumber =jtxtDisplay.getText()+ jBn6.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBn6ActionPerformed

    private void jBn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBn8ActionPerformed
        String Enternumber =jtxtDisplay.getText()+ jBn8.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBn8ActionPerformed

    private void jBn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBn11ActionPerformed
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations="+";
    }//GEN-LAST:event_jBn11ActionPerformed

    private void jBn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBn12ActionPerformed
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations="-";
    }//GEN-LAST:event_jBn12ActionPerformed

    private void jBn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBn16ActionPerformed
        String Enternumber =jtxtDisplay.getText()+ jBn16.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBn16ActionPerformed

    private void jBn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBn15ActionPerformed
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops=ops * (-1);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBn15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBn1;
    private javax.swing.JButton jBn10;
    private javax.swing.JButton jBn11;
    private javax.swing.JButton jBn12;
    private javax.swing.JButton jBn13;
    private javax.swing.JButton jBn14;
    private javax.swing.JButton jBn15;
    private javax.swing.JButton jBn16;
    private javax.swing.JButton jBn17;
    private javax.swing.JButton jBn18;
    private javax.swing.JButton jBn2;
    private javax.swing.JButton jBn3;
    private javax.swing.JButton jBn4;
    private javax.swing.JButton jBn5;
    private javax.swing.JButton jBn6;
    private javax.swing.JButton jBn7;
    private javax.swing.JButton jBn8;
    private javax.swing.JButton jBn9;
    private javax.swing.JTextField jtxtDisplay;
    // End of variables declaration//GEN-END:variables
}
